name = "molly-memo-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787

[[d1_databases]]
binding = "DB"
database_name = "molly-memo-db-dev"
database_id = "0fcdf688-248f-455d-8ee1-7b790e7a22d2"

[[r2_buckets]]
binding = "R2"
bucket_name = "molly-memo-bucket-dev"

[vars]
APP_ENV = "development"

[env.production]
name = "molly-memo-worker-prod"

[env.production.vars]
APP_ENV = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "molly-memo-db-prod"
database_id = "97c85fb2-d0b5-4406-ade9-c4a76f5095f2"

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "molly-memo-bucket-prod"