name = "molly-memo"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 默认环境 (dev)
[dev]
port = 8787

[vars]
APP_ENV = "development"

[[d1_databases]]
binding = "DB"
database_name = "molly-memo-db-dev"
database_id = "0fcdf688-248f-455d-8ee1-7b790e7a22d2"
migrations_dir = "drizzle/migrations"

[[r2_buckets]]
binding = "R2"
bucket_name = "molly-memo-bucket-dev"

# 生产环境 (production)
[env.production]
name = "molly-memo-worker-prod"

[env.production.vars]
APP_ENV = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "molly-memo-db-prod"
database_id = "97c85fb2-d0b5-4406-ade9-c4a76f5095f2"
migrations_dir = "drizzle/migrations"

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "molly-memo-bucket-prod"
